name: New Table
description: File a bug report

body:
- type: markdown
  attributes:
    value: "some values"
    
- type: textarea
  attributes:
      label: "Description"
      description: "Details on the generic pupose of the table (optional)"
      value: "ex. an adverse event table"
