name: New Table

body:

- type: markdown
  attributes:
    value: "Please describe the characteristics of the required table"

- type: input
  id: table_name
  attributes:
    label: "Table Name"
    description: "Standard name of the table"
    placeholder: "ex. AET02"
      
- type: input
  id: table_pupose
  attributes:
    label: "Description"
    description: "Details on the generic pupose of the table (optional)"
    placeholder: "ex. an adverse event table"
    
- type: input
  id: analysis_dataset
  attributes:
    label: "Analysis dataset"
    description: "Name of the standard dataset input"
    placeholder: "ex. ADAE"
    
- type: textarea
  id: analysis_filtering
  attribute:
    label: Analysis filtering
    description: Filtering criteria of the input
    value: ex. ANL01FL="Y"
    
    
 
   
